spring:
  web:
    resources:
      static-locations: classpath:/,classpath:/resources/
  application:
    name: chat-service
  r2dbc:
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  webflux:
    base-path: /chat
  data:
    r2dbc:
      repositories:
        enabled: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: '8082'
