spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri:  http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/users/**
        - id: order-service
          uri:  http://order-service.default.svc.cluster.local:8083
          predicates:
            - Path=/orders/**
        - id: chat-service
          uri:  http://chat-service.default.svc.cluster.local:8082
          predicates:
            - Path=/chat/**
        - id: auth-service
          uri:  http://auth-service.default.svc.cluster.local:9000
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<path>.*), /$\{path}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service.default.svc.cluster.local:9000
server:
  port: 8089
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true


logging:
  level:
    root: DEBUG
