spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<path>.*), /$\{path}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    root: DEBUG
